### ISSUE TITLE
not following deployment status for system jobs

### ISSUE THREAD

**Issue by jippi** [hashicorp/levant#256] opened 2018-11-26 11:10 UTC
**Description**

When Levant submits a system job, it returns right away, instead of tracking rollout of the code 

**Relevant Nomad job specification file**

```hcl
job "apacta-web" {
  datacenters = ["eu-central-1"]
  priority    = 50
  region      = "primary"
  type        = "system"

  constraint {
    attribute = "${node.class}"
    value     = "web"
  }

  update {
    max_parallel      = 1
    health_check      = "checks"
    min_healthy_time  = "10s"
    healthy_deadline  = "5m"
    progress_deadline = "10m"
  }

  # ...
}
```

**Output of `levant version`:**

```
jrasell/levant:0.2.5
```

**Output of `nomad version`:**

```
0.8.6
```

**Comment by jrasell** [comment] 2018-12-19 15:57
@jippi do you have anymore details here or info? I have just been testing locally using master and it seems to be working as expected.

```jrasell@lluna  ~/go/src/github.com/jrasell/levant   master  ./levant-local deploy example.nomad
2018-12-19T15:55:56Z |INFO| levant/plan: job is a new addition to the cluster
2018-12-19T15:55:57Z |INFO| levant/deploy: job is not running, using template file group counts job_id=example
2018-12-19T15:55:57Z |INFO| levant/deploy: triggering a deployment job_id=example
2018-12-19T15:55:58Z |INFO| levant/deploy: evaluation 780f852b-5377-ffae-9039-d8abef5a6910 finished successfully job_id=example
2018-12-19T15:55:58Z |INFO| levant/job_status_checker: job has status running job_id=example
2018-12-19T15:55:58Z |INFO| levant/job_status_checker: task redis in allocation 74ebede8-8a30-5c83-f6b8-1263144f0642 now in pending state job_id=example
2018-12-19T15:55:59Z |INFO| levant/job_status_checker: task redis in allocation 74ebede8-8a30-5c83-f6b8-1263144f0642 now in running state job_id=example
2018-12-19T15:55:59Z |INFO| levant/job_status_checker: all allocations in deployment of job are running job_id=example
2018-12-19T15:55:59Z |INFO| levant/deploy: job deployment successful job_id=example
```

**Comment by jippi** [comment] 2018-12-19 16:47
can you trigger an update for the job as well? thats where I've observed it

**Comment by jrasell** [comment] 2020-11-27 09:39
Closing as I was unable to reproduce and there where no further updates. Please re-open if you believe this is still an issue.

**Closed by jrasell** 2020-11-27 09:39 UTC
Labels: bug, deployment
